set MATLAB=C:\Program Files\Polyspace\R2021a
"%MATLAB%\bin\win64\gmake" -f mbd3.mk  RSIM_SOLVER_SELECTION=1 PCMATLABROOT="C:\\Program Files\\Polyspace\\R2021a" EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 EXTMODE_TRANSPORT=0 TMW_EXTMODE_TESTING=0 RSIM_PARAMETER_LOADING=1 OPTS="-DNRT -DRSIM_WITH_SL_SOLVER -DRSIM_PARAMETER_LOADING -DTID01EQ=0"
